A10
allopez7/algorithm pull request #10
Opened 2017-10-12 18:00 UTC by allopez7

2017-10-12 19:12 UTC, seemcat requested changes

2017-10-12 19:12 UTC, seemcat commented on solutions/10.js
> +  if(i > num1 && i > num2){
if (i >num1 && num2)

2017-10-12 19:12 UTC, seemcat commented on test/10.js
> +  }
} else {
bigger = numTwo;
}

2017-10-13 20:34 UTC, bramakrishna16 approved these changes

2017-10-13 20:40 UTC, allopez7 commented on solutions/10.js
> +  if(i > num1 && i > num2){
this does not work for me.

2017-10-13 20:41 UTC, allopez7 reviewed
changes made!

2017-10-13 20:42 UTC, merged